"""initial v1 domain schema

Revision ID: 412e9051869a
Revises: 
Create Date: 2026-08-26 02:05:43.246423

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '412e9051869a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_products',
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('canonical_brand', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=160), nullable=True),
    sa.Column('subcategory', sa.String(length=160), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'review', 'deprecated')", name=op.f('ck_canonical_products_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_products'))
    )
    op.create_index(op.f('ix_canonical_products_category'), 'canonical_products', ['category'], unique=False)
    op.create_index('ix_canonical_products_name_brand', 'canonical_products', ['normalized_name', 'canonical_brand'], unique=False)
    op.create_table('restaurants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurants'))
    )
    op.create_table('suppliers',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('code', name=op.f('uq_suppliers_code'))
    )
    op.create_table('users',
    sa.Column('auth_provider_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('auth_provider_id', name=op.f('uq_users_auth_provider_id'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('product_variants',
    sa.Column('canonical_product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('base_unit', sa.String(length=10), nullable=False),
    sa.Column('pack_count', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('normalized_pack_text', sa.String(length=160), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("base_unit IN ('kg', 'l', 'piece')", name=op.f('ck_product_variants_valid_base_unit')),
    sa.CheckConstraint('pack_count > 0', name=op.f('ck_product_variants_positive_pack_count')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_product_variants_positive_quantity')),
    sa.CheckConstraint('total_quantity > 0', name=op.f('ck_product_variants_positive_total_quantity')),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], name=op.f('fk_product_variants_canonical_product_id_canonical_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('canonical_product_id', 'quantity', 'base_unit', 'pack_count', 'normalized_pack_text', name=op.f('uq_product_variants_canonical_product_id'))
    )
    op.create_index(op.f('ix_product_variants_canonical_product_id'), 'product_variants', ['canonical_product_id'], unique=False)
    op.create_table('restaurant_locations',
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_beta_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_restaurant_locations_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurant_locations')),
    sa.UniqueConstraint('restaurant_id', 'label', name=op.f('uq_restaurant_locations_restaurant_id'))
    )
    op.create_index('ix_restaurant_locations_restaurant_beta', 'restaurant_locations', ['restaurant_id', 'is_beta_default'], unique=False)
    op.create_index(op.f('ix_restaurant_locations_restaurant_id'), 'restaurant_locations', ['restaurant_id'], unique=False)
    op.create_table('restaurant_memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'manager', 'member')", name=op.f('ck_restaurant_memberships_valid_role')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_restaurant_memberships_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_restaurant_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'restaurant_id', name=op.f('pk_restaurant_memberships'))
    )
    op.create_table('supplier_locations',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('external_location_id', sa.String(length=255), nullable=False),
    sa.Column('location_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('location_metadata', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("location_type IN ('store', 'warehouse', 'zone', 'city', 'fulfilment_center', 'anonymous', 'unknown')", name=op.f('ck_supplier_locations_valid_location_type')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_locations_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_locations')),
    sa.UniqueConstraint('supplier_id', 'external_location_id', name=op.f('uq_supplier_locations_supplier_id'))
    )
    op.create_index(op.f('ix_supplier_locations_supplier_id'), 'supplier_locations', ['supplier_id'], unique=False)
    op.create_table('supplier_products',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('external_product_id', sa.String(length=255), nullable=False),
    sa.Column('external_variant_id', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=500), nullable=False),
    sa.Column('source_brand', sa.String(length=200), nullable=True),
    sa.Column('source_category', sa.String(length=200), nullable=True),
    sa.Column('source_pack_text', sa.String(length=200), nullable=True),
    sa.Column('product_url', sa.String(length=2048), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('product_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_products_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_products')),
    sa.UniqueConstraint('supplier_id', 'external_product_id', 'external_variant_id', name=op.f('uq_supplier_products_supplier_id'))
    )
    op.create_index('ix_supplier_products_source_brand', 'supplier_products', ['source_brand'], unique=False)
    op.create_index('ix_supplier_products_source_name', 'supplier_products', ['source_name'], unique=False)
    op.create_index(op.f('ix_supplier_products_supplier_id'), 'supplier_products', ['supplier_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_location_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_product_id', sa.Uuid(), nullable=False),
    sa.Column('base_unit', sa.String(length=10), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("base_unit IN ('kg', 'l', 'piece')", name=op.f('ck_inventory_items_valid_base_unit')),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], name=op.f('fk_inventory_items_canonical_product_id_canonical_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_inventory_items_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_location_id'], ['restaurant_locations.id'], name=op.f('fk_inventory_items_restaurant_location_id_restaurant_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items')),
    sa.UniqueConstraint('restaurant_id', 'restaurant_location_id', 'canonical_product_id', 'base_unit', name=op.f('uq_inventory_items_restaurant_id'))
    )
    op.create_table('product_matches',
    sa.Column('supplier_product_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('match_method', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("review_status IN ('AUTO_MATCH', 'REVIEW', 'NO_MATCH', 'MANUAL_MATCH')", name=op.f('ck_product_matches_valid_review_status')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_product_matches_valid_confidence')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_product_matches_product_variant_id_product_variants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_products.id'], name=op.f('fk_product_matches_supplier_product_id_supplier_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_matches')),
    sa.UniqueConstraint('supplier_product_id', 'product_variant_id', name=op.f('uq_product_matches_supplier_product_id'))
    )
    op.create_index(op.f('ix_product_matches_product_variant_id'), 'product_matches', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_product_matches_supplier_product_id'), 'product_matches', ['supplier_product_id'], unique=False)
    op.create_table('purchases',
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_location_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_purchases_nonnegative_total')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_purchases_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_purchases_restaurant_id_restaurants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_location_id'], ['restaurant_locations.id'], name=op.f('fk_purchases_restaurant_location_id_restaurant_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchases_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases'))
    )
    op.create_index('ix_purchases_restaurant_purchased', 'purchases', ['restaurant_id', 'purchased_at'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_location_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expected_count', sa.Integer(), nullable=True),
    sa.Column('observed_count', sa.Integer(), nullable=False),
    sa.Column('failed_page_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('run_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('running', 'complete', 'partial', 'failed', 'suspicious_zero', 'interrupted')", name=op.f('ck_scrape_runs_valid_status')),
    sa.CheckConstraint('failed_page_count >= 0', name=op.f('ck_scrape_runs_nonnegative_failed_pages')),
    sa.CheckConstraint('observed_count >= 0', name=op.f('ck_scrape_runs_nonnegative_observed_count')),
    sa.CheckConstraint('warning_count >= 0', name=op.f('ck_scrape_runs_nonnegative_warnings')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_scrape_runs_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_location_id'], ['supplier_locations.id'], name=op.f('fk_scrape_runs_supplier_location_id_supplier_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_runs'))
    )
    op.create_index(op.f('ix_scrape_runs_status'), 'scrape_runs', ['status'], unique=False)
    op.create_index('ix_scrape_runs_supplier_location_started', 'scrape_runs', ['supplier_id', 'supplier_location_id', 'started_at'], unique=False)
    op.create_table('supplier_location_mappings',
    sa.Column('restaurant_location_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_location_id', sa.Uuid(), nullable=False),
    sa.Column('resolution_method', sa.String(length=30), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("resolution_method IN ('verified_api', 'verified_session', 'manual', 'legacy', 'fallback', 'unknown')", name=op.f('ck_supplier_location_mappings_valid_resolution_method')),
    sa.ForeignKeyConstraint(['restaurant_location_id'], ['restaurant_locations.id'], name=op.f('fk_supplier_location_mappings_restaurant_location_id_restaurant_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_location_mappings_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_location_id'], ['supplier_locations.id'], name=op.f('fk_supplier_location_mappings_supplier_location_id_supplier_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_location_mappings')),
    sa.UniqueConstraint('restaurant_location_id', 'supplier_id', 'supplier_location_id', name=op.f('uq_supplier_location_mappings_restaurant_location_id'))
    )
    op.create_index(op.f('ix_supplier_location_mappings_restaurant_location_id'), 'supplier_location_mappings', ['restaurant_location_id'], unique=False)
    op.create_table('supplier_offers',
    sa.Column('supplier_product_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_location_id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_mrp', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_availability', sa.Boolean(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_misses', sa.Integer(), nullable=False),
    sa.Column('current_observation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('consecutive_misses >= 0', name=op.f('ck_supplier_offers_nonnegative_misses')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_supplier_offers_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_location_id'], ['supplier_locations.id'], name=op.f('fk_supplier_offers_supplier_location_id_supplier_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_products.id'], name=op.f('fk_supplier_offers_supplier_product_id_supplier_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_offers')),
    sa.UniqueConstraint('supplier_product_id', 'product_variant_id', 'supplier_location_id', name=op.f('uq_supplier_offers_supplier_product_id'))
    )
    op.create_index('ix_supplier_offers_location_seen', 'supplier_offers', ['supplier_location_id', 'last_seen_at'], unique=False)
    op.create_index(op.f('ix_supplier_offers_supplier_product_id'), 'supplier_offers', ['supplier_product_id'], unique=False)
    op.create_index('ix_supplier_offers_variant_active', 'supplier_offers', ['product_variant_id', 'active'], unique=False)
    op.create_table('expense_entries',
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_location_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('expense_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_expense_entries_nonnegative_amount')),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name=op.f('fk_expense_entries_purchase_id_purchases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_expense_entries_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_location_id'], ['restaurant_locations.id'], name=op.f('fk_expense_entries_restaurant_location_id_restaurant_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_expense_entries_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_entries')),
    sa.UniqueConstraint('purchase_id', name=op.f('uq_expense_entries_purchase_id'))
    )
    op.create_index('ix_expense_entries_restaurant_date', 'expense_entries', ['restaurant_id', 'expense_date'], unique=False)
    op.create_table('price_observations',
    sa.Column('supplier_offer_id', sa.Uuid(), nullable=False),
    sa.Column('scrape_run_id', sa.Uuid(), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_reference', sa.String(length=2048), nullable=True),
    sa.Column('legacy_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('mrp IS NULL OR mrp >= 0', name=op.f('ck_price_observations_nonnegative_mrp')),
    sa.CheckConstraint('price IS NULL OR price >= 0', name=op.f('ck_price_observations_nonnegative_price')),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], name=op.f('fk_price_observations_scrape_run_id_scrape_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_offer_id'], ['supplier_offers.id'], name=op.f('fk_price_observations_supplier_offer_id_supplier_offers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_observations'))
    )
    op.create_index('ix_price_observations_offer_observed', 'price_observations', ['supplier_offer_id', 'observed_at'], unique=False)
    op.create_index('ix_price_observations_run', 'price_observations', ['scrape_run_id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('purchase_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_product_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_offer_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_product_url_snapshot', sa.String(length=2048), nullable=True),
    sa.Column('packs', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('scraped_price_snapshot', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('actual_unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('actual_total_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('actual_total_price >= 0', name=op.f('ck_purchase_items_nonnegative_actual_total_price')),
    sa.CheckConstraint('actual_unit_price >= 0', name=op.f('ck_purchase_items_nonnegative_actual_unit_price')),
    sa.CheckConstraint('packs > 0', name=op.f('ck_purchase_items_positive_packs')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_purchase_items_positive_quantity')),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], name=op.f('fk_purchase_items_canonical_product_id_canonical_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_purchase_items_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name=op.f('fk_purchase_items_purchase_id_purchases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_offer_id'], ['supplier_offers.id'], name=op.f('fk_purchase_items_supplier_offer_id_supplier_offers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_items'))
    )
    op.create_index(op.f('ix_purchase_items_purchase_id'), 'purchase_items', ['purchase_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('inventory_item_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('purchase_item_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("transaction_type IN ('purchase', 'manual_add', 'manual_remove', 'correction')", name=op.f('ck_inventory_transactions_valid_transaction_type')),
    sa.CheckConstraint('quantity_delta <> 0', name=op.f('ck_inventory_transactions_nonzero_delta')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_inventory_transactions_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_inventory_transactions_inventory_item_id_inventory_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_item_id'], ['purchase_items.id'], name=op.f('fk_inventory_transactions_purchase_item_id_purchase_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_transactions'))
    )
    op.create_index('ix_inventory_transactions_item_created', 'inventory_transactions', ['inventory_item_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_transactions_item_created', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_purchase_items_purchase_id'), table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index('ix_price_observations_run', table_name='price_observations')
    op.drop_index('ix_price_observations_offer_observed', table_name='price_observations')
    op.drop_table('price_observations')
    op.drop_index('ix_expense_entries_restaurant_date', table_name='expense_entries')
    op.drop_table('expense_entries')
    op.drop_index('ix_supplier_offers_variant_active', table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_supplier_product_id'), table_name='supplier_offers')
    op.drop_index('ix_supplier_offers_location_seen', table_name='supplier_offers')
    op.drop_table('supplier_offers')
    op.drop_index(op.f('ix_supplier_location_mappings_restaurant_location_id'), table_name='supplier_location_mappings')
    op.drop_table('supplier_location_mappings')
    op.drop_index('ix_scrape_runs_supplier_location_started', table_name='scrape_runs')
    op.drop_index(op.f('ix_scrape_runs_status'), table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index('ix_purchases_restaurant_purchased', table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_product_matches_supplier_product_id'), table_name='product_matches')
    op.drop_index(op.f('ix_product_matches_product_variant_id'), table_name='product_matches')
    op.drop_table('product_matches')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_supplier_products_supplier_id'), table_name='supplier_products')
    op.drop_index('ix_supplier_products_source_name', table_name='supplier_products')
    op.drop_index('ix_supplier_products_source_brand', table_name='supplier_products')
    op.drop_table('supplier_products')
    op.drop_index(op.f('ix_supplier_locations_supplier_id'), table_name='supplier_locations')
    op.drop_table('supplier_locations')
    op.drop_table('restaurant_memberships')
    op.drop_index(op.f('ix_restaurant_locations_restaurant_id'), table_name='restaurant_locations')
    op.drop_index('ix_restaurant_locations_restaurant_beta', table_name='restaurant_locations')
    op.drop_table('restaurant_locations')
    op.drop_index(op.f('ix_product_variants_canonical_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('restaurants')
    op.drop_index('ix_canonical_products_name_brand', table_name='canonical_products')
    op.drop_index(op.f('ix_canonical_products_category'), table_name='canonical_products')
    op.drop_table('canonical_products')
    # ### end Alembic commands ###
